# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gmassoni <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/07/28 18:41:32 by gmassoni          #+#    #+#              #
#    Updated: 2023/07/28 19:22:37 by gmassoni         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc

CFLAGS = -Wall -Wextra -Werror

SRCS = ft_display_file.c

NAME = ft_display_file

all: ${NAME}

${NAME}:
	${CC} ${CFLAGS}

clean:

fclean: clean
	rm -f ${NAME}

.PHONY: all clean fclean
